name: vector_graphics_generator_annotations
description: An annotation package for Flutter that converts SVGs automatically into vector_graphics.
version: 0.0.1
homepage: https://github.com/dnfield/vector_graphics

environment:
  sdk: ">=2.17.0 <3.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
